### PR TITLE
using fallback image and avoiding reload loop

### LINKED ISSUE #532: Image component, handle onError = null
handle edgecase, if fallback image fails, prevent loop

probable state needed that keeps track of attempted fallback

### PR DESCRIPTION
**Pull request by zavelevsky**
fixes #532

### CODE REVIEW

File: src/components/image/useFallbackImage.tsx [hunk 1]
```diff
@@ -0,0 +1,16 @@
+import { useState } from 'react';
+
+export function useFallbackImage(src: string | undefined, fallbackSrc: string) {
+  const [failed, setFailed] = useState(false);
+  const imageOnErrorHandler = (
+    // @ts-ignore
```
Comment (pingustar) [inline src/components/image/useFallbackImage.tsx:6]: is this ts-ignore needed?

**Review by pingustar — COMMENTED** [review]
LGTM

**Review by pingustar — APPROVED** [review]
