### PR TITLE
Potfolio Positions Fix

### LINKED ISSUE #517: Portfolio - override selected tokenlist
as a user, when i open the portfolio, i would like to see all tokens that are staked into bancor.

for this to happen:
1. ignore the user enabled tokenlist and pull data from all tokenlists

### PR DESCRIPTION
**Pull request by RanCohenn**
Fixes #517

### CODE REVIEW

File: src/redux/bancor/bancor.ts [hunk 1]
```diff
@@ -55,16 +62,24 @@ export const {
...
   updateTokens,
   setBntPrice,
 } = bancorSlice.actions;
 
 export const getTokenById = (id: string) =>
   createSelector(
-    (state: RootState) => state.bancor.tokens,
-    (tokens: Token[]) => {
-      return tokens.find((t) => t.address === id);
+    (state: RootState) => state.bancor,
```
Comment (zavelevsky) [inline src/redux/bancor/bancor.ts:73]:
```js
const tokens = state => state.bancor.tokens;
const apiTokens = state => bancor.apiTokens;
export const getTokenById = (id: string) =>
  createSelector(
    tokens,
    apiTokens,
   (tokens, apiTokens) => {
     // ...
    }
  )

**Review by zavelevsky — DISMISSED** [review]
LGTM

**Comment by ashachaf** [comment]
- [ ] toggle on/off to any token list has some delay
flow:
open token lists management
click to enable
expected: immediatly see the toggle change
actual: it takes 4-5 seconds until something happens.
